import type { Recipe } from "./types";

export const sampleRecipes: (Recipe & { image: string; category: string })[] = [
  {
    name: "Grilled Lemon Herb Chicken",
    description: "Juicy grilled chicken marinated in fresh lemon, garlic, and Mediterranean herbs. A protein-packed classic.",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&h=400&fit=crop",
    category: "High Protein",
    servings: 4,
    prepTime: "15 min",
    cookTime: "25 min",
    estimatedCost: "$12 – $15",
    ingredients: [
      { item: "Chicken breasts", amount: "4 pieces" },
      { item: "Lemon juice", amount: "3 tbsp" },
      { item: "Olive oil", amount: "2 tbsp" },
      { item: "Garlic cloves", amount: "4, minced" },
      { item: "Dried oregano", amount: "1 tsp" },
      { item: "Fresh rosemary", amount: "2 sprigs" },
      { item: "Salt & pepper", amount: "To taste" },
    ],
    steps: [
      "Mix lemon juice, olive oil, garlic, oregano, salt, and pepper in a bowl.",
      "Marinate chicken breasts for at least 30 minutes (or overnight for best results).",
      "Preheat grill to medium-high heat (about 400°F).",
      "Grill chicken 6–7 minutes per side until internal temp reaches 165°F.",
      "Rest for 5 minutes, garnish with fresh rosemary, and serve.",
    ],
    nutrition: {
      calories: 320,
      protein: "42g",
      carbs: "2g",
      fat: "14g",
      fiber: "0g",
      sugar: "0g",
      sodium: "380mg",
    },
    tips: "Pound chicken to even thickness for uniform cooking. Let it rest after grilling to keep it juicy.",
  },
  {
    name: "Creamy Tuscan Pasta",
    description: "Rich and creamy sun-dried tomato pasta with spinach and parmesan. Ready in under 30 minutes.",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 4,
    prepTime: "10 min",
    cookTime: "20 min",
    estimatedCost: "$10 – $13",
    ingredients: [
      { item: "Penne pasta", amount: "400g" },
      { item: "Heavy cream", amount: "1 cup" },
      { item: "Sun-dried tomatoes", amount: "½ cup" },
      { item: "Fresh spinach", amount: "2 cups" },
      { item: "Parmesan cheese", amount: "½ cup, grated" },
      { item: "Garlic", amount: "3 cloves" },
      { item: "Italian seasoning", amount: "1 tsp" },
    ],
    steps: [
      "Cook penne in salted boiling water until al dente. Reserve 1 cup pasta water, then drain.",
      "Sauté minced garlic in olive oil for 1 minute over medium heat.",
      "Add sun-dried tomatoes and cook for 2 minutes.",
      "Pour in heavy cream, add Italian seasoning, and simmer for 3–4 minutes.",
      "Toss in spinach until wilted, add parmesan, then combine with pasta. Add pasta water as needed.",
    ],
    nutrition: {
      calories: 520,
      protein: "18g",
      carbs: "62g",
      fat: "22g",
      fiber: "4g",
      sugar: "6g",
      sodium: "450mg",
    },
    tips: "Use bronze-cut pasta — it holds sauce much better. A splash of pasta water makes the sauce silky.",
  },
  {
    name: "Thai Basil Stir-Fry",
    description: "A quick, fiery stir-fry with ground chicken, Thai basil, and chili. Bold flavors in 15 minutes.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 2,
    prepTime: "5 min",
    cookTime: "10 min",
    estimatedCost: "$8 – $10",
    ingredients: [
      { item: "Ground chicken", amount: "300g" },
      { item: "Thai basil leaves", amount: "1 cup" },
      { item: "Thai chili", amount: "3, sliced" },
      { item: "Garlic", amount: "5 cloves, minced" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Oyster sauce", amount: "1 tbsp" },
      { item: "Sugar", amount: "1 tsp" },
    ],
    steps: [
      "Heat oil in a wok on high heat until smoking.",
      "Add garlic and chili, stir for 30 seconds.",
      "Add ground chicken and break it apart. Cook for 4–5 minutes until browned.",
      "Add soy sauce, oyster sauce, and sugar. Toss to coat.",
      "Kill the heat, fold in Thai basil until just wilted. Serve over jasmine rice.",
    ],
    nutrition: {
      calories: 380,
      protein: "34g",
      carbs: "8g",
      fat: "22g",
      fiber: "1g",
      sugar: "4g",
      sodium: "820mg",
    },
    tips: "Use holy basil if you can find it — it's more authentic and has a peppery kick.",
  },
  {
    name: "Avocado & Black Bean Bowl",
    description: "A vibrant, plant-powered bowl loaded with black beans, avocado, corn, and a zesty lime dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    category: "Vegan",
    servings: 2,
    prepTime: "10 min",
    cookTime: "0 min",
    estimatedCost: "$6 – $8",
    ingredients: [
      { item: "Black beans (canned)", amount: "1 can, drained" },
      { item: "Avocado", amount: "1 large" },
      { item: "Corn kernels", amount: "½ cup" },
      { item: "Cherry tomatoes", amount: "1 cup, halved" },
      { item: "Red onion", amount: "¼, diced" },
      { item: "Lime juice", amount: "2 tbsp" },
      { item: "Cilantro", amount: "¼ cup, chopped" },
    ],
    steps: [
      "Combine black beans, corn, cherry tomatoes, and red onion in a large bowl.",
      "Whisk together lime juice, olive oil, salt, and cumin for the dressing.",
      "Slice the avocado and fan it over the bowl.",
      "Drizzle the lime dressing, top with cilantro, and serve chilled.",
    ],
    nutrition: {
      calories: 340,
      protein: "14g",
      carbs: "42g",
      fat: "16g",
      fiber: "18g",
      sugar: "4g",
      sodium: "280mg",
    },
    tips: "Add a fried egg on top for extra protein. Swap corn for roasted sweet potato in fall.",
  },
  {
    name: "Classic Beef Tacos",
    description: "Seasoned ground beef tacos with all the fixings — cheese, salsa, lettuce, and sour cream.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 4,
    prepTime: "10 min",
    cookTime: "15 min",
    estimatedCost: "$11 – $14",
    ingredients: [
      { item: "Ground beef", amount: "500g" },
      { item: "Taco shells", amount: "8" },
      { item: "Taco seasoning", amount: "2 tbsp" },
      { item: "Shredded lettuce", amount: "1 cup" },
      { item: "Cheddar cheese", amount: "½ cup, shredded" },
      { item: "Salsa", amount: "½ cup" },
      { item: "Sour cream", amount: "¼ cup" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat, breaking it into crumbles.",
      "Drain excess fat, then add taco seasoning and ¼ cup water. Simmer 5 minutes.",
      "Warm taco shells in the oven at 350°F for 3 minutes.",
      "Fill each shell with seasoned beef, then layer lettuce, cheese, salsa, and sour cream.",
    ],
    nutrition: {
      calories: 440,
      protein: "28g",
      carbs: "24g",
      fat: "26g",
      fiber: "2g",
      sugar: "3g",
      sodium: "680mg",
    },
    tips: "Use corn tortillas and char them on an open flame for restaurant-quality tacos.",
  },
  {
    name: "Salmon Teriyaki Bowl",
    description: "Glazed teriyaki salmon over steamed rice with edamame, cucumber, and sesame. Clean eating made delicious.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop",
    category: "Healthy",
    servings: 2,
    prepTime: "10 min",
    cookTime: "15 min",
    estimatedCost: "$14 – $18",
    ingredients: [
      { item: "Salmon fillets", amount: "2 pieces" },
      { item: "Soy sauce", amount: "3 tbsp" },
      { item: "Mirin", amount: "2 tbsp" },
      { item: "Honey", amount: "1 tbsp" },
      { item: "Steamed rice", amount: "2 cups" },
      { item: "Edamame", amount: "½ cup" },
      { item: "Cucumber", amount: "1, sliced" },
    ],
    steps: [
      "Mix soy sauce, mirin, and honey to make the teriyaki glaze.",
      "Pan-sear salmon skin-side down for 4 minutes, flip, and cook 3 more minutes.",
      "Pour glaze over salmon in the last minute of cooking. Let it caramelize.",
      "Serve salmon over steamed rice with edamame, cucumber, and a sprinkle of sesame seeds.",
    ],
    nutrition: {
      calories: 480,
      protein: "38g",
      carbs: "48g",
      fat: "14g",
      fiber: "3g",
      sugar: "10g",
      sodium: "720mg",
    },
    tips: "Pat salmon dry before searing for a crispier skin. Don't move it once it hits the pan.",
  },
  {
    name: "Mushroom Risotto",
    description: "Creamy, earthy Italian risotto with mixed mushrooms, parmesan, and a touch of white wine.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop",
    category: "Vegetarian",
    servings: 4,
    prepTime: "10 min",
    cookTime: "30 min",
    estimatedCost: "$10 – $13",
    ingredients: [
      { item: "Arborio rice", amount: "1½ cups" },
      { item: "Mixed mushrooms", amount: "300g, sliced" },
      { item: "Vegetable broth", amount: "4 cups, warm" },
      { item: "White wine", amount: "½ cup" },
      { item: "Parmesan", amount: "½ cup, grated" },
      { item: "Butter", amount: "2 tbsp" },
      { item: "Shallot", amount: "1, finely diced" },
    ],
    steps: [
      "Sauté mushrooms in butter until golden. Set aside.",
      "In the same pan, cook shallot until soft. Add arborio rice and toast 2 minutes.",
      "Deglaze with white wine, stirring until absorbed.",
      "Add warm broth one ladle at a time, stirring continuously, until rice is creamy and al dente (~18 min).",
      "Fold in mushrooms, parmesan, and an extra knob of butter. Season and serve immediately.",
    ],
    nutrition: {
      calories: 420,
      protein: "14g",
      carbs: "58g",
      fat: "14g",
      fiber: "3g",
      sugar: "2g",
      sodium: "520mg",
    },
    tips: "Never stop stirring — it releases the starch and makes risotto creamy. Use hot broth, never cold.",
  },
  {
    name: "Spicy Shrimp Tacos",
    description: "Blackened shrimp tacos with mango salsa and chipotle crema. A crowd-pleaser in 20 minutes.",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 3,
    prepTime: "10 min",
    cookTime: "8 min",
    estimatedCost: "$13 – $16",
    ingredients: [
      { item: "Large shrimp", amount: "400g, peeled" },
      { item: "Blackening seasoning", amount: "2 tbsp" },
      { item: "Small tortillas", amount: "6" },
      { item: "Mango", amount: "1, diced" },
      { item: "Red onion", amount: "¼, finely diced" },
      { item: "Sour cream", amount: "¼ cup" },
      { item: "Chipotle in adobo", amount: "1 tbsp" },
    ],
    steps: [
      "Toss shrimp with blackening seasoning until evenly coated.",
      "Sear shrimp in a hot skillet with oil, 2 minutes per side.",
      "Mix diced mango, red onion, lime juice, and cilantro for the salsa.",
      "Blend sour cream with chipotle for the crema.",
      "Assemble tacos: tortilla → shrimp → mango salsa → chipotle crema.",
    ],
    nutrition: {
      calories: 360,
      protein: "30g",
      carbs: "34g",
      fat: "12g",
      fiber: "3g",
      sugar: "12g",
      sodium: "590mg",
    },
    tips: "Don't overcrowd the pan — shrimp need space to sear, not steam.",
  },
  // --- High Protein ---
  {
    name: "Steak & Sweet Potato",
    description: "Pan-seared sirloin steak with roasted sweet potato wedges and a garlic herb butter.",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&h=400&fit=crop",
    category: "High Protein",
    servings: 2,
    prepTime: "10 min",
    cookTime: "20 min",
    estimatedCost: "$16 – $20",
    ingredients: [
      { item: "Sirloin steak", amount: "2 pieces" },
      { item: "Sweet potatoes", amount: "2 medium" },
      { item: "Butter", amount: "2 tbsp" },
      { item: "Garlic", amount: "3 cloves" },
      { item: "Fresh thyme", amount: "3 sprigs" },
      { item: "Olive oil", amount: "2 tbsp" },
    ],
    steps: [
      "Cut sweet potatoes into wedges, toss with olive oil, salt, and pepper. Roast at 425°F for 20 min.",
      "Season steaks generously with salt and pepper.",
      "Sear in a hot cast-iron skillet 4 min per side for medium-rare.",
      "Add butter, garlic, and thyme to the pan. Baste the steak for 1 minute.",
      "Rest 5 minutes before slicing. Serve with sweet potato wedges.",
    ],
    nutrition: { calories: 560, protein: "46g", carbs: "38g", fat: "24g", fiber: "5g", sugar: "8g", sodium: "420mg" },
    tips: "Let steaks come to room temperature before cooking for even searing.",
  },
  {
    name: "Greek Chicken Power Bowl",
    description: "Grilled chicken over quinoa with feta, olives, cucumber, and a tangy tzatziki drizzle.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
    category: "High Protein",
    servings: 2,
    prepTime: "15 min",
    cookTime: "15 min",
    estimatedCost: "$11 – $14",
    ingredients: [
      { item: "Chicken breast", amount: "2 pieces" },
      { item: "Quinoa", amount: "1 cup" },
      { item: "Cucumber", amount: "1, diced" },
      { item: "Feta cheese", amount: "¼ cup" },
      { item: "Kalamata olives", amount: "¼ cup" },
      { item: "Tzatziki", amount: "½ cup" },
    ],
    steps: [
      "Cook quinoa according to package directions.",
      "Season chicken with oregano, garlic powder, salt, and pepper. Grill 6 min per side.",
      "Slice chicken and arrange over quinoa with cucumber, olives, and feta.",
      "Drizzle generously with tzatziki and a squeeze of lemon.",
    ],
    nutrition: { calories: 480, protein: "44g", carbs: "36g", fat: "18g", fiber: "4g", sugar: "3g", sodium: "560mg" },
    tips: "Make extra quinoa — it keeps well for meal prep throughout the week.",
  },
  // --- Comfort Food ---
  {
    name: "Mac & Cheese (From Scratch)",
    description: "Ultra-creamy baked mac and cheese with a crispy breadcrumb topping. Pure comfort.",
    image: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 6,
    prepTime: "15 min",
    cookTime: "30 min",
    estimatedCost: "$8 – $11",
    ingredients: [
      { item: "Elbow macaroni", amount: "450g" },
      { item: "Sharp cheddar", amount: "2 cups, shredded" },
      { item: "Gruyère", amount: "1 cup, shredded" },
      { item: "Whole milk", amount: "2½ cups" },
      { item: "Butter", amount: "3 tbsp" },
      { item: "Flour", amount: "3 tbsp" },
      { item: "Panko breadcrumbs", amount: "½ cup" },
    ],
    steps: [
      "Cook macaroni until just under al dente. Drain and set aside.",
      "Melt butter, whisk in flour, cook 1 min. Slowly pour in milk, whisking constantly.",
      "Simmer until thick (~5 min), then remove from heat and stir in cheeses until melted.",
      "Fold in pasta, transfer to a baking dish. Top with buttered panko.",
      "Bake at 375°F for 20 minutes until golden and bubbly.",
    ],
    nutrition: { calories: 580, protein: "24g", carbs: "52g", fat: "30g", fiber: "2g", sugar: "5g", sodium: "620mg" },
    tips: "Mix in a pinch of mustard powder and smoked paprika for next-level flavor.",
  },
  {
    name: "Chicken Pot Pie",
    description: "Flaky golden crust filled with tender chicken, vegetables, and a rich creamy sauce.",
    image: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 6,
    prepTime: "20 min",
    cookTime: "35 min",
    estimatedCost: "$12 – $15",
    ingredients: [
      { item: "Cooked chicken", amount: "3 cups, shredded" },
      { item: "Frozen peas & carrots", amount: "1½ cups" },
      { item: "Pie crust", amount: "2 sheets" },
      { item: "Heavy cream", amount: "1 cup" },
      { item: "Chicken broth", amount: "1 cup" },
      { item: "Butter", amount: "3 tbsp" },
      { item: "Flour", amount: "3 tbsp" },
    ],
    steps: [
      "Make the filling: melt butter, whisk in flour, then add broth and cream. Simmer until thick.",
      "Stir in chicken, peas, carrots, salt, and pepper.",
      "Line a pie dish with one crust, pour in filling, cover with second crust. Crimp edges.",
      "Cut slits in the top for steam. Brush with egg wash.",
      "Bake at 400°F for 30–35 minutes until golden brown.",
    ],
    nutrition: { calories: 490, protein: "28g", carbs: "34g", fat: "26g", fiber: "3g", sugar: "4g", sodium: "580mg" },
    tips: "Use rotisserie chicken for a huge time saver without sacrificing flavor.",
  },
  // --- Quick & Easy ---
  {
    name: "15-Minute Garlic Shrimp Pasta",
    description: "Buttery garlic shrimp tossed with linguine, red pepper flakes, and fresh parsley.",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 2,
    prepTime: "5 min",
    cookTime: "10 min",
    estimatedCost: "$12 – $15",
    ingredients: [
      { item: "Linguine", amount: "200g" },
      { item: "Large shrimp", amount: "300g" },
      { item: "Butter", amount: "3 tbsp" },
      { item: "Garlic", amount: "5 cloves, sliced" },
      { item: "Red pepper flakes", amount: "½ tsp" },
      { item: "Lemon", amount: "1" },
      { item: "Fresh parsley", amount: "¼ cup" },
    ],
    steps: [
      "Boil linguine in salted water until al dente. Reserve ½ cup pasta water.",
      "Melt butter in a large skillet, sauté garlic and pepper flakes for 1 minute.",
      "Add shrimp, cook 2 minutes per side until pink.",
      "Toss in pasta, add pasta water as needed, squeeze lemon, and garnish with parsley.",
    ],
    nutrition: { calories: 440, protein: "32g", carbs: "48g", fat: "14g", fiber: "2g", sugar: "2g", sodium: "480mg" },
    tips: "Don't overcook the shrimp — they turn rubbery fast. Pull them the second they curl.",
  },
  {
    name: "Egg Fried Rice",
    description: "Restaurant-style fried rice with fluffy eggs, green onions, and a hint of sesame. Uses leftover rice.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 2,
    prepTime: "5 min",
    cookTime: "8 min",
    estimatedCost: "$3 – $5",
    ingredients: [
      { item: "Day-old rice", amount: "3 cups" },
      { item: "Eggs", amount: "3" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Sesame oil", amount: "1 tsp" },
      { item: "Green onions", amount: "3, sliced" },
      { item: "Garlic", amount: "2 cloves" },
      { item: "Vegetable oil", amount: "2 tbsp" },
    ],
    steps: [
      "Heat oil in a wok on high. Scramble eggs, break into pieces, set aside.",
      "Add more oil, stir-fry garlic 30 seconds, then add rice. Press and toss for 3–4 minutes.",
      "Add soy sauce around the edges of the wok so it sizzles.",
      "Return eggs, drizzle sesame oil, toss with green onions, and serve immediately.",
    ],
    nutrition: { calories: 380, protein: "14g", carbs: "52g", fat: "14g", fiber: "1g", sugar: "1g", sodium: "620mg" },
    tips: "Day-old cold rice is essential — fresh rice will be mushy. Spread it on a sheet pan to dry if needed.",
  },
  // --- Vegan ---
  {
    name: "Coconut Chickpea Curry",
    description: "A rich, aromatic curry with chickpeas, spinach, and coconut milk. Warm spices, zero compromise.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
    category: "Vegan",
    servings: 4,
    prepTime: "10 min",
    cookTime: "20 min",
    estimatedCost: "$6 – $9",
    ingredients: [
      { item: "Chickpeas (canned)", amount: "2 cans" },
      { item: "Coconut milk", amount: "1 can" },
      { item: "Spinach", amount: "3 cups" },
      { item: "Onion", amount: "1, diced" },
      { item: "Garlic & ginger", amount: "1 tbsp each, minced" },
      { item: "Curry powder", amount: "2 tbsp" },
      { item: "Diced tomatoes", amount: "1 can" },
    ],
    steps: [
      "Sauté onion until soft. Add garlic, ginger, and curry powder, cook 1 min.",
      "Pour in diced tomatoes and coconut milk. Stir and bring to a simmer.",
      "Add chickpeas and cook for 15 minutes until sauce thickens.",
      "Fold in spinach until wilted. Season with salt and lime juice. Serve over rice.",
    ],
    nutrition: { calories: 360, protein: "14g", carbs: "40g", fat: "18g", fiber: "12g", sugar: "6g", sodium: "380mg" },
    tips: "Toast your curry powder in the dry pan first — it blooms the spices and doubles the flavor.",
  },
  {
    name: "Roasted Cauliflower Tacos",
    description: "Crispy spiced cauliflower with pickled onions, avocado crema, and fresh cilantro on corn tortillas.",
    image: "https://images.unsplash.com/photo-1564093497595-593b96d80180?w=600&h=400&fit=crop",
    category: "Vegan",
    servings: 3,
    prepTime: "10 min",
    cookTime: "25 min",
    estimatedCost: "$7 – $10",
    ingredients: [
      { item: "Cauliflower", amount: "1 head, florets" },
      { item: "Cumin", amount: "1 tsp" },
      { item: "Smoked paprika", amount: "1 tsp" },
      { item: "Corn tortillas", amount: "6" },
      { item: "Avocado", amount: "1" },
      { item: "Red onion", amount: "½, thinly sliced" },
      { item: "Lime", amount: "2" },
    ],
    steps: [
      "Toss cauliflower with oil, cumin, paprika, salt. Roast at 425°F for 25 min until crispy.",
      "Quick-pickle red onion in lime juice and a pinch of sugar while cauliflower roasts.",
      "Mash avocado with lime juice and salt for the crema.",
      "Warm tortillas, fill with cauliflower, top with pickled onion and avocado crema.",
    ],
    nutrition: { calories: 280, protein: "8g", carbs: "36g", fat: "14g", fiber: "10g", sugar: "5g", sodium: "320mg" },
    tips: "Don't crowd the baking sheet — space between florets = more crispy edges.",
  },
  // --- Healthy ---
  {
    name: "Mediterranean Grilled Fish",
    description: "Light, flaky white fish with cherry tomatoes, capers, olives, and a lemon-herb sauce.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&h=400&fit=crop",
    category: "Healthy",
    servings: 2,
    prepTime: "10 min",
    cookTime: "12 min",
    estimatedCost: "$12 – $16",
    ingredients: [
      { item: "White fish fillets", amount: "2 pieces" },
      { item: "Cherry tomatoes", amount: "1 cup" },
      { item: "Kalamata olives", amount: "¼ cup" },
      { item: "Capers", amount: "1 tbsp" },
      { item: "Lemon", amount: "1" },
      { item: "Fresh dill", amount: "2 tbsp" },
      { item: "Olive oil", amount: "2 tbsp" },
    ],
    steps: [
      "Season fish with salt, pepper, and olive oil.",
      "Pan-sear fish 4 min per side until golden and flaky.",
      "In the same pan, sauté tomatoes, olives, and capers for 2 minutes.",
      "Squeeze lemon over everything, garnish with dill, and serve with a side salad.",
    ],
    nutrition: { calories: 290, protein: "34g", carbs: "8g", fat: "14g", fiber: "2g", sugar: "4g", sodium: "480mg" },
    tips: "Use sea bass or cod for the best results. Don't flip the fish more than once.",
  },
  {
    name: "Turkey Lettuce Wraps",
    description: "Light and crunchy lettuce cups filled with savory ground turkey, water chestnuts, and hoisin glaze.",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&h=400&fit=crop",
    category: "Healthy",
    servings: 3,
    prepTime: "10 min",
    cookTime: "10 min",
    estimatedCost: "$9 – $12",
    ingredients: [
      { item: "Ground turkey", amount: "400g" },
      { item: "Butter lettuce", amount: "1 head" },
      { item: "Water chestnuts", amount: "½ cup, diced" },
      { item: "Hoisin sauce", amount: "3 tbsp" },
      { item: "Soy sauce", amount: "1 tbsp" },
      { item: "Garlic", amount: "3 cloves" },
      { item: "Green onions", amount: "3, sliced" },
    ],
    steps: [
      "Brown ground turkey with garlic in a skillet, breaking it apart.",
      "Add water chestnuts, hoisin, soy sauce, and a splash of rice vinegar.",
      "Cook 2–3 minutes until sauce thickens and coats the turkey.",
      "Spoon mixture into lettuce cups, top with green onions and sesame seeds.",
    ],
    nutrition: { calories: 260, protein: "28g", carbs: "14g", fat: "10g", fiber: "2g", sugar: "6g", sodium: "520mg" },
    tips: "Use iceberg lettuce for extra crunch. Serve with sriracha on the side for heat lovers.",
  },
  // --- Vegetarian ---
  {
    name: "Caprese Stuffed Portobello",
    description: "Juicy portobello mushrooms stuffed with fresh mozzarella, tomatoes, basil, and a balsamic reduction.",
    image: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&h=400&fit=crop",
    category: "Vegetarian",
    servings: 2,
    prepTime: "10 min",
    cookTime: "15 min",
    estimatedCost: "$8 – $11",
    ingredients: [
      { item: "Portobello caps", amount: "4 large" },
      { item: "Fresh mozzarella", amount: "200g, sliced" },
      { item: "Tomato", amount: "2, sliced" },
      { item: "Fresh basil", amount: "¼ cup" },
      { item: "Balsamic vinegar", amount: "3 tbsp" },
      { item: "Olive oil", amount: "2 tbsp" },
    ],
    steps: [
      "Remove stems from portobellos, brush with olive oil, season with salt and pepper.",
      "Bake gill-side up at 400°F for 8 minutes.",
      "Layer tomato and mozzarella slices inside each cap. Bake 5 more minutes until cheese melts.",
      "Simmer balsamic in a small pan until reduced by half. Drizzle over mushrooms with fresh basil.",
    ],
    nutrition: { calories: 320, protein: "18g", carbs: "12g", fat: "22g", fiber: "3g", sugar: "8g", sodium: "340mg" },
    tips: "Pat mushrooms dry before oiling — wet mushrooms steam instead of roasting.",
  },
  {
    name: "Spinach & Ricotta Stuffed Shells",
    description: "Jumbo pasta shells loaded with creamy ricotta and spinach, baked in marinara sauce.",
    image: "https://images.unsplash.com/photo-1587740908075-9e245070dfaa?w=600&h=400&fit=crop",
    category: "Vegetarian",
    servings: 4,
    prepTime: "20 min",
    cookTime: "25 min",
    estimatedCost: "$9 – $12",
    ingredients: [
      { item: "Jumbo pasta shells", amount: "20" },
      { item: "Ricotta cheese", amount: "2 cups" },
      { item: "Frozen spinach", amount: "1 cup, thawed" },
      { item: "Egg", amount: "1" },
      { item: "Marinara sauce", amount: "2 cups" },
      { item: "Mozzarella", amount: "1 cup, shredded" },
      { item: "Parmesan", amount: "¼ cup" },
    ],
    steps: [
      "Cook shells until just under al dente. Drain and let cool slightly.",
      "Mix ricotta, squeezed-dry spinach, egg, parmesan, salt, and pepper.",
      "Spread half the marinara in a baking dish. Fill each shell and arrange snugly.",
      "Top with remaining marinara and mozzarella. Bake at 375°F for 25 min until bubbly.",
    ],
    nutrition: { calories: 420, protein: "22g", carbs: "44g", fat: "18g", fiber: "4g", sugar: "6g", sodium: "580mg" },
    tips: "Squeeze ALL the water from the spinach — soggy filling ruins the dish.",
  },
];
