import type { Recipe } from "./types";

export const sampleRecipes: (Recipe & { image: string; category: string })[] = [
  {
    name: "Grilled Lemon Herb Chicken",
    description: "Juicy grilled chicken marinated in fresh lemon, garlic, and Mediterranean herbs. A protein-packed classic.",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&h=400&fit=crop",
    category: "High Protein",
    servings: 4,
    prepTime: "15 min",
    cookTime: "25 min",
    estimatedCost: "$12 – $15",
    ingredients: [
      { item: "Chicken breasts", amount: "4 pieces" },
      { item: "Lemon juice", amount: "3 tbsp" },
      { item: "Olive oil", amount: "2 tbsp" },
      { item: "Garlic cloves", amount: "4, minced" },
      { item: "Dried oregano", amount: "1 tsp" },
      { item: "Fresh rosemary", amount: "2 sprigs" },
      { item: "Salt & pepper", amount: "To taste" },
    ],
    steps: [
      "Mix lemon juice, olive oil, garlic, oregano, salt, and pepper in a bowl.",
      "Marinate chicken breasts for at least 30 minutes (or overnight for best results).",
      "Preheat grill to medium-high heat (about 400°F).",
      "Grill chicken 6–7 minutes per side until internal temp reaches 165°F.",
      "Rest for 5 minutes, garnish with fresh rosemary, and serve.",
    ],
    nutrition: {
      calories: 320,
      protein: "42g",
      carbs: "2g",
      fat: "14g",
      fiber: "0g",
      sugar: "0g",
      sodium: "380mg",
    },
    tips: "Pound chicken to even thickness for uniform cooking. Let it rest after grilling to keep it juicy.",
  },
  {
    name: "Creamy Tuscan Pasta",
    description: "Rich and creamy sun-dried tomato pasta with spinach and parmesan. Ready in under 30 minutes.",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 4,
    prepTime: "10 min",
    cookTime: "20 min",
    estimatedCost: "$10 – $13",
    ingredients: [
      { item: "Penne pasta", amount: "400g" },
      { item: "Heavy cream", amount: "1 cup" },
      { item: "Sun-dried tomatoes", amount: "½ cup" },
      { item: "Fresh spinach", amount: "2 cups" },
      { item: "Parmesan cheese", amount: "½ cup, grated" },
      { item: "Garlic", amount: "3 cloves" },
      { item: "Italian seasoning", amount: "1 tsp" },
    ],
    steps: [
      "Cook penne in salted boiling water until al dente. Reserve 1 cup pasta water, then drain.",
      "Sauté minced garlic in olive oil for 1 minute over medium heat.",
      "Add sun-dried tomatoes and cook for 2 minutes.",
      "Pour in heavy cream, add Italian seasoning, and simmer for 3–4 minutes.",
      "Toss in spinach until wilted, add parmesan, then combine with pasta. Add pasta water as needed.",
    ],
    nutrition: {
      calories: 520,
      protein: "18g",
      carbs: "62g",
      fat: "22g",
      fiber: "4g",
      sugar: "6g",
      sodium: "450mg",
    },
    tips: "Use bronze-cut pasta — it holds sauce much better. A splash of pasta water makes the sauce silky.",
  },
  {
    name: "Thai Basil Stir-Fry",
    description: "A quick, fiery stir-fry with ground chicken, Thai basil, and chili. Bold flavors in 15 minutes.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 2,
    prepTime: "5 min",
    cookTime: "10 min",
    estimatedCost: "$8 – $10",
    ingredients: [
      { item: "Ground chicken", amount: "300g" },
      { item: "Thai basil leaves", amount: "1 cup" },
      { item: "Thai chili", amount: "3, sliced" },
      { item: "Garlic", amount: "5 cloves, minced" },
      { item: "Soy sauce", amount: "2 tbsp" },
      { item: "Oyster sauce", amount: "1 tbsp" },
      { item: "Sugar", amount: "1 tsp" },
    ],
    steps: [
      "Heat oil in a wok on high heat until smoking.",
      "Add garlic and chili, stir for 30 seconds.",
      "Add ground chicken and break it apart. Cook for 4–5 minutes until browned.",
      "Add soy sauce, oyster sauce, and sugar. Toss to coat.",
      "Kill the heat, fold in Thai basil until just wilted. Serve over jasmine rice.",
    ],
    nutrition: {
      calories: 380,
      protein: "34g",
      carbs: "8g",
      fat: "22g",
      fiber: "1g",
      sugar: "4g",
      sodium: "820mg",
    },
    tips: "Use holy basil if you can find it — it's more authentic and has a peppery kick.",
  },
  {
    name: "Avocado & Black Bean Bowl",
    description: "A vibrant, plant-powered bowl loaded with black beans, avocado, corn, and a zesty lime dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    category: "Vegan",
    servings: 2,
    prepTime: "10 min",
    cookTime: "0 min",
    estimatedCost: "$6 – $8",
    ingredients: [
      { item: "Black beans (canned)", amount: "1 can, drained" },
      { item: "Avocado", amount: "1 large" },
      { item: "Corn kernels", amount: "½ cup" },
      { item: "Cherry tomatoes", amount: "1 cup, halved" },
      { item: "Red onion", amount: "¼, diced" },
      { item: "Lime juice", amount: "2 tbsp" },
      { item: "Cilantro", amount: "¼ cup, chopped" },
    ],
    steps: [
      "Combine black beans, corn, cherry tomatoes, and red onion in a large bowl.",
      "Whisk together lime juice, olive oil, salt, and cumin for the dressing.",
      "Slice the avocado and fan it over the bowl.",
      "Drizzle the lime dressing, top with cilantro, and serve chilled.",
    ],
    nutrition: {
      calories: 340,
      protein: "14g",
      carbs: "42g",
      fat: "16g",
      fiber: "18g",
      sugar: "4g",
      sodium: "280mg",
    },
    tips: "Add a fried egg on top for extra protein. Swap corn for roasted sweet potato in fall.",
  },
  {
    name: "Classic Beef Tacos",
    description: "Seasoned ground beef tacos with all the fixings — cheese, salsa, lettuce, and sour cream.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    category: "Comfort Food",
    servings: 4,
    prepTime: "10 min",
    cookTime: "15 min",
    estimatedCost: "$11 – $14",
    ingredients: [
      { item: "Ground beef", amount: "500g" },
      { item: "Taco shells", amount: "8" },
      { item: "Taco seasoning", amount: "2 tbsp" },
      { item: "Shredded lettuce", amount: "1 cup" },
      { item: "Cheddar cheese", amount: "½ cup, shredded" },
      { item: "Salsa", amount: "½ cup" },
      { item: "Sour cream", amount: "¼ cup" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat, breaking it into crumbles.",
      "Drain excess fat, then add taco seasoning and ¼ cup water. Simmer 5 minutes.",
      "Warm taco shells in the oven at 350°F for 3 minutes.",
      "Fill each shell with seasoned beef, then layer lettuce, cheese, salsa, and sour cream.",
    ],
    nutrition: {
      calories: 440,
      protein: "28g",
      carbs: "24g",
      fat: "26g",
      fiber: "2g",
      sugar: "3g",
      sodium: "680mg",
    },
    tips: "Use corn tortillas and char them on an open flame for restaurant-quality tacos.",
  },
  {
    name: "Salmon Teriyaki Bowl",
    description: "Glazed teriyaki salmon over steamed rice with edamame, cucumber, and sesame. Clean eating made delicious.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop",
    category: "Healthy",
    servings: 2,
    prepTime: "10 min",
    cookTime: "15 min",
    estimatedCost: "$14 – $18",
    ingredients: [
      { item: "Salmon fillets", amount: "2 pieces" },
      { item: "Soy sauce", amount: "3 tbsp" },
      { item: "Mirin", amount: "2 tbsp" },
      { item: "Honey", amount: "1 tbsp" },
      { item: "Steamed rice", amount: "2 cups" },
      { item: "Edamame", amount: "½ cup" },
      { item: "Cucumber", amount: "1, sliced" },
    ],
    steps: [
      "Mix soy sauce, mirin, and honey to make the teriyaki glaze.",
      "Pan-sear salmon skin-side down for 4 minutes, flip, and cook 3 more minutes.",
      "Pour glaze over salmon in the last minute of cooking. Let it caramelize.",
      "Serve salmon over steamed rice with edamame, cucumber, and a sprinkle of sesame seeds.",
    ],
    nutrition: {
      calories: 480,
      protein: "38g",
      carbs: "48g",
      fat: "14g",
      fiber: "3g",
      sugar: "10g",
      sodium: "720mg",
    },
    tips: "Pat salmon dry before searing for a crispier skin. Don't move it once it hits the pan.",
  },
  {
    name: "Mushroom Risotto",
    description: "Creamy, earthy Italian risotto with mixed mushrooms, parmesan, and a touch of white wine.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop",
    category: "Vegetarian",
    servings: 4,
    prepTime: "10 min",
    cookTime: "30 min",
    estimatedCost: "$10 – $13",
    ingredients: [
      { item: "Arborio rice", amount: "1½ cups" },
      { item: "Mixed mushrooms", amount: "300g, sliced" },
      { item: "Vegetable broth", amount: "4 cups, warm" },
      { item: "White wine", amount: "½ cup" },
      { item: "Parmesan", amount: "½ cup, grated" },
      { item: "Butter", amount: "2 tbsp" },
      { item: "Shallot", amount: "1, finely diced" },
    ],
    steps: [
      "Sauté mushrooms in butter until golden. Set aside.",
      "In the same pan, cook shallot until soft. Add arborio rice and toast 2 minutes.",
      "Deglaze with white wine, stirring until absorbed.",
      "Add warm broth one ladle at a time, stirring continuously, until rice is creamy and al dente (~18 min).",
      "Fold in mushrooms, parmesan, and an extra knob of butter. Season and serve immediately.",
    ],
    nutrition: {
      calories: 420,
      protein: "14g",
      carbs: "58g",
      fat: "14g",
      fiber: "3g",
      sugar: "2g",
      sodium: "520mg",
    },
    tips: "Never stop stirring — it releases the starch and makes risotto creamy. Use hot broth, never cold.",
  },
  {
    name: "Spicy Shrimp Tacos",
    description: "Blackened shrimp tacos with mango salsa and chipotle crema. A crowd-pleaser in 20 minutes.",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&h=400&fit=crop",
    category: "Quick & Easy",
    servings: 3,
    prepTime: "10 min",
    cookTime: "8 min",
    estimatedCost: "$13 – $16",
    ingredients: [
      { item: "Large shrimp", amount: "400g, peeled" },
      { item: "Blackening seasoning", amount: "2 tbsp" },
      { item: "Small tortillas", amount: "6" },
      { item: "Mango", amount: "1, diced" },
      { item: "Red onion", amount: "¼, finely diced" },
      { item: "Sour cream", amount: "¼ cup" },
      { item: "Chipotle in adobo", amount: "1 tbsp" },
    ],
    steps: [
      "Toss shrimp with blackening seasoning until evenly coated.",
      "Sear shrimp in a hot skillet with oil, 2 minutes per side.",
      "Mix diced mango, red onion, lime juice, and cilantro for the salsa.",
      "Blend sour cream with chipotle for the crema.",
      "Assemble tacos: tortilla → shrimp → mango salsa → chipotle crema.",
    ],
    nutrition: {
      calories: 360,
      protein: "30g",
      carbs: "34g",
      fat: "12g",
      fiber: "3g",
      sugar: "12g",
      sodium: "590mg",
    },
    tips: "Don't overcrowd the pan — shrimp need space to sear, not steam.",
  },
];
